#server:
#  port: 8082
#spring:
#  profiles:
#    active: qa
#---
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    password: pass
#    url: jdbc:h2:mem:dcbapp
#    username: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#---
#spring:
#  profiles: qa
#  datasource:
#    driverClassName: org.h2.Driver
#    password: pass
#    url: jdbc:h2:mem:dcbapp
#    username: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#---
#spring:
#  profiles: prod
#  datasource:
#    driverClassName: org.h2.Driver
#    password: pass
#    url: jdbc:h2:mem:dcbapp
#    username: sa
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
